CREATE TABLE site
(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(40),
    html TEXT NOT NULL
);

CREATE UNIQUE INDEX unique_site_id ON site ( id );

INSERT INTO site VALUES (1, "about", "&lt;div class=&quot;span10 offset1&quot;&gt;&lt;div class=&quot;row&quot;&gt;&lt;div class=&quot;span3&quot; style=&quot;margin-top: 30px;&quot;&gt;&lt;div class=&quot;row&quot;&gt;&lt;img src=&quot;http://severinelenglet.eu/assets/img/about0.jpg&quot; style=&quot;width:100%&quot; /&gt;&lt;/div&gt;&lt;div class=&quot;row&quot;&gt;&lt;img src=&quot;http://severinelenglet.eu/assets/img/about2.jpg&quot; style=&quot;float:left; width:50%&quot; /&gt;&lt;img src=&quot;http://severinelenglet.eu/assets/img/about1.jpg&quot; style=&quot;float:right; width:50%&quot; /&gt;&lt;/div&gt;&lt;p&gt;&lt;a href=&quot;http://severinelenglet.eu/public/CV.pdf&quot;&gt;Download my Curriculum vit&amp;aelig;&lt;/a&gt;&lt;/p&gt;&lt;/div&gt;&lt;div class=&quot;span5&quot;&gt;&lt;h1&gt;About&lt;/h1&gt;&lt;p&gt;Coming from France, I have worked as a journalist and filmmaker for different print media,televisions,institutions and NGOs from all over the world. I produce reports, short films, images films anddocumentary films in different countries (Europe, India, Nicaragua, Swaziland, C&amp;ocirc;te d&amp;rsquo;Ivoire,Ghana&amp;hellip;).&lt;/p&gt;&lt;p&gt;As a Video Journalist, I have substantial expertise in all aspects of Video Journalism includingwriting, interviewing, filming and editing. As a Filmmaker, I coordinate all the processes of makingafilm (from an initial story idea, through scriptwriting, shooting, editing and directing). As aVideotrainer, I coach groups, help individuals in developing their media skills (how to use a camera, howtowrite a video story, how to edit a film&amp;hellip;)&lt;/p&gt;&lt;p&gt;As an Audio-Visual Coordinator with the European civil society organisation European Alternatives, Icoordinate both international teams and transnational film projects. I have also worked on the videoproduction and distribution strategy which supports their communications and advocacy goals such asthe promotion of democracy, equality, and civil society participation throughout Europe.&lt;/p&gt;&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;")